# Generated by Django 5.0 on 2024-01-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='customer', max_length=20),
            preserve_default=False,
        ),
    ]
